name: Create a Gist with all project files

on:
  push:
    branches:
      - main  # Runs when changes are pushed to 'main'

jobs:
  create_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Collect all text files
        run: |
          echo "Collecting all text files..."
          
          FILES_JSON="{ \"description\": \"Filtered project files\", \"public\": true, \"files\": {"
          
          for FILE in $(find . -type f \( -name "*.txt" -o -name "*.md" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.html" -o -name "*.css" \) -not -path "./.git/*" -not -path "./.github/workflows/*"); do
            CONTENT=$(cat "$FILE" | jq -Rs .)  # Convert file content to JSON-safe format
            FILES_JSON="$FILES_JSON \"$FILE\": { \"content\": $CONTENT },"
          done
          
          FILES_JSON="${FILES_JSON%,} }}"  # Remove trailing comma and close JSON structure
          
          curl -X POST https://api.github.com/gists \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "$FILES_JSON"
