name: Create a Gist uploading all text files

on:
  push:
    branches:
      - main

jobs:
  create_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq zip

      - name: Collect, compress, and upload text files as a gist
        run: |
          echo "Collecting all text files..."

          # ✅ Create a compressed archive of text files
          ZIP_FILE="project_files.zip"
          find D:/PROJECTS/ANGULAR/PERSONAL_EXPENSE_TRACKER/backend D:/PROJECTS/ANGULAR/PERSONAL_EXPENSE_TRACKER/frontend -type f
          \( -name "*.txt" -o -name "*.md" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.html" -o -name "*.css" \) -print | zip -@ $ZIP_FILE

          # ✅ Convert ZIP file content to Base64 (GitHub Gist doesn't support binary files)
          BASE64_CONTENT=$(base64 -w 0 $ZIP_FILE)

          # ✅ Create JSON payload for Gist
          FILES_JSON="{ \"description\": \"Compressed project files\", \"public\": true, \"files\": { \"project_files.zip\": { \"content\": \"$BASE64_CONTENT\" } } }"

          # ✅ Upload Gist & Capture Response
          RESPONSE=$(curl -X POST https://api.github.com/gists \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "$FILES_JSON")

          if echo "$RESPONSE" | jq -e '.id'; then
            echo "Gist successfully created!"
          else
            echo "Failed to create gist. Response: $RESPONSE"
            exit 1
          fi
