name: Create a Gist uploading all text files

on:
  push:
    branches:
      - main  # Runs when changes are pushed to 'main'

jobs:
  create_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # ✅ Ensures repo is checked out before running script

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq  # ✅ Ensures jq is installed

      - name: Collect and upload all text files in one gist
        run: |
          echo "Collecting all text files..."
          
          FILES_JSON="{ \"description\": \"Complete project files\", \"public\": true, \"files\": {"

          # ✅ Search inside backend/ and frontend/ instead of "."
          for FILE in $(find backend frontend -type f \( -name "*.txt" -o -name "*.md" -o -name "*.js" -o -name "*.ts" -o -name "*.java" -o -name "*.html" -o -name "*.css" \)); do
            if [ ! -s "$FILE" ]; then  # ✅ Skip empty files to prevent "gist file cannot be blank" error
              echo "Skipping empty file: $FILE"
              continue
            fi

            FILENAME=$(basename "$FILE")
            CONTENT=$(jq -Rs . < "$FILE")
            FILES_JSON="$FILES_JSON \"$FILENAME\": { \"content\": $CONTENT },"
          done

          FILES_JSON="${FILES_JSON%,} }}"  # ✅ Close JSON object

          # ✅ Upload all files in a single gist
          curl -X POST https://api.github.com/gists \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -d "$FILES_JSON"

          echo "Uploaded all files in one gist"
