- name: Create a Gist with all project files
  run: |
    echo "Archiving all project files..."
    
    # Create a ZIP archive of the entire repository
    zip -r project_files.zip . -x ".git/*" ".github/workflows/*"

    # Convert ZIP to base64 to send via API
    BASE64_ZIP=$(base64 project_files.zip)

    curl -X POST https://api.github.com/gists \
    -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
    -d '{
      "description": "Full project archive",
      "public": true,
      "files": {
        "project_files.zip": {
          "content": "'"$BASE64_ZIP"'"
        }
      }
    }'
